# Generated by Django 3.2.5 on 2021-07-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='transactioninfo',
            name='tags',
        ),
        migrations.AddField(
            model_name='expense',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tag'),
        ),
        migrations.AddField(
            model_name='transactioninfo',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.expense'),
        ),
    ]
