# Generated by Django 3.2.5 on 2021-07-15 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210712_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioninfo',
            name='tag',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
